
CREATE TABLE IF NOT EXISTS addresses (
id UUID PRIMARY KEY NOT NULL,
country VARCHAR(75) NOT NULL,
city VARCHAR(75) NOT NULL,
street VARCHAR(75) NOT NULL
);

CREATE TABLE IF NOT EXISTS clients (
id UUID PRIMARY KEY NOT NULL,
client_name VARCHAR(50) NOT NULL,
client_surname VARCHAR(50) NOT NULL,
birth_date DATE NOT NULL,
gender VARCHAR(7) NOT NULL,
registration_date DATE NOT NULL,
address_id UUID NOT NULL,
FOREIGN KEY (address_id) REFERENCES address(id)
);

CREATE TABLE IF NOT EXISTS products (
id UUID PRIMARY KEY NOT NULL,
name VARCHAR(50) NOT NULL,
category VARCHAR(13) NOT NULL,
price DOUBLE PRECISION NOT NULL,
available_stock INT NOT NULL,
last_update_date DATE NOT NULL,
supplier_id UUID NOT NULL,
FOREIGN KEY (supplier_id) REFERENCES suppliers(id)
);

CREATE TABLE IF NOT EXISTS suppliers (
id UUID PRIMARY KEY NOT NULL,
name VARCHAR(50) NOT NULL,
address_id UUID NOT NULL,
phone_number VARCHAR(20) NOT NULL,
FOREIGN KEY (address_id) REFERENCES address(id)
);

CREATE TABLE IF NOT EXISTS images (
id UUID PRIMARY KEY NOT NULL,
image BYTEA NOT NULL
);

